import type { Product, Testimonial } from './types';

export const products: Product[] = [
  {
    id: 'prod_1',
    name: 'Classic Oak Armchair',
    description: 'A timeless piece, handcrafted from solid oak with a natural finish. Perfect for any living room.',
    price: 450,
    imageId: 'product1',
    category: 'Chairs',
    material: 'Oak',
    rating: 4.8,
  },
  {
    id: 'prod_2',
    name: 'Walnut Coffee Table',
    description: 'Minimalist design meets rich walnut wood. This coffee table is a statement of elegance.',
    price: 620,
    imageId: 'product2',
    category: 'Tables',
    material: 'Walnut',
    rating: 4.9,
  },
  {
    id: 'prod_3',
    name: 'Linen Blend Sofa',
    description: 'A comfortable and stylish 3-seater sofa upholstered in a premium linen blend fabric.',
    price: 1250,
    imageId: 'product3',
    category: 'Sofas',
    material: 'Linen',
    rating: 4.7,
  },
  {
    id: 'prod_4',
    name: 'Modern Bookshelf',
    description: 'Display your collection in style with this sleek and sturdy bookshelf, made from reclaimed pine.',
    price: 780,
    imageId: 'product4',
    category: 'Storage',
    material: 'Pine',
    rating: 4.6,
  },
  {
    id: 'prod_5',
    name: 'Ergonomic Desk Chair',
    description: 'Designed for comfort and style, this chair features a beautiful ash wood frame and leather seat.',
    price: 530,
    imageId: 'product5',
    category: 'Chairs',
    material: 'Ash',
    rating: 4.8,
  },
  {
    id: 'prod_6',
    name: 'Round Dining Table',
    description: 'Gather your family around this stunning round dining table, crafted from dark walnut for a dramatic effect.',
    price: 1400,
    imageId: 'product6',
    category: 'Tables',
    material: 'Walnut',
    rating: 4.9,
  },
  {
    id: 'prod_7',
    name: 'Velvet Ottoman',
    description: 'A touch of luxury for any room. This plush velvet ottoman comes in a variety of rich colors.',
    price: 320,
    imageId: 'product7',
    category: 'Sofas',
    material: 'Velvet',
    rating: 4.5,
  },
  {
    id: 'prod_8',
    name: 'Floating Wall Shelves',
    description: 'Solid oak floating shelves that provide a clean, modern way to display decor.',
    price: 180,
    imageId: 'product8',
    category: 'Storage',
    material: 'Oak',
    rating: 4.7,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 'test_1',
    quote: "The quality of our new dining table is simply outstanding. You can feel the craftsmanship. It's the centerpiece of our home now.",
    customerName: 'Emily Carter',
    customerTitle: 'Homeowner, New York',
    imageId: 'avatar1',
  },
  {
    id: 'test_2',
    quote: "Artisan Showcase transformed our living space. The sofa is not only beautiful but incredibly comfortable. The whole process was seamless.",
    customerName: 'Michael Chen',
    customerTitle: 'Interior Designer',
    imageId: 'avatar2',
  },
  {
    id: 'test_3',
    quote: "I was looking for a unique bookshelf and found the perfect one here. It's a true work of art. I get compliments on it all the time!",
    customerName: 'Sarah Jenkins',
    customerTitle: 'Architect, Chicago',
    imageId: 'avatar3',
  },
   {
    id: 'test_4',
    quote: "From the wood grain on my armchair to the soft-close drawers on my sideboard, every detail is perfect. Highly recommended.",
    customerName: 'David Lee',
    customerTitle: 'Art Director',
    imageId: 'avatar4',
  },
];
